import { useState } from 'react'

const SECTIONS = {
  disclaimer: {
    title: 'Disclaimer',
    icon: '⚖️',
    content: `
## Important Disclaimer

Jyotish ("the App") provides Vedic astrological readings, horoscopes, birth chart calculations, and AI-powered consultations for **entertainment, educational, and self-reflection purposes only**.

### Not Professional Advice
The content provided by Jyotish does not constitute:
- Medical, psychiatric, or psychological advice
- Legal advice
- Financial or investment advice
- Career counselling
- Relationship counselling

Always consult qualified professionals for decisions related to health, law, finance, and personal matters.

### Nature of Astrology
Vedic astrology is a traditional belief system. Astrological predictions and readings are based on classical texts and interpretations. Results may vary and are not guaranteed. Jyotish makes no claim that astrological readings will predict the future with certainty.

### AI-Generated Content
Readings marked "AI-powered" are generated by artificial intelligence (Google Gemini) based on astrological parameters. These are not statements of fact and should be treated as creative interpretations.

### No Liability
Jyotish, its owners, operators, and affiliates shall not be liable for any decisions made by users based on content provided by the App. Users assume full responsibility for how they use astrological guidance.

### Vulnerable Users
If you are experiencing a mental health crisis, please contact a qualified mental health professional. Do not rely on astrological guidance in emergency situations.
    `
  },
  terms: {
    title: 'Terms & Conditions',
    icon: '📋',
    content: `
## Terms & Conditions

**Last updated: May 1, 2026**
**Effective date: May 1, 2026**

These Terms & Conditions ("Terms") govern your use of Jyotish, operated by Deepanshu Rajoria ("we", "us", "our"), accessible at myjyotish-ai.in.

### 1. Acceptance of Terms
By accessing or using Jyotish, you confirm that you are at least 18 years of age and agree to these Terms. If you do not agree, please do not use the App.

### 2. Services Provided
Jyotish provides:
- Vedic birth chart (Kundali) calculations
- AI-powered horoscope readings (weekly, monthly, annual)
- Sun sign and Moon sign forecasts
- AI chat consultation with Jyotish Acharya

All content is for entertainment and self-reflection purposes. See our Disclaimer for important limitations.

### 3. Premium Subscription

**Free Tier:** Weekly horoscope, weekly Sun sign forecast, 3 AI chat messages per day, basic Kundali chart.

**Premium Plans:**
- Monthly Plan: ₹49 per month
- Annual Plan: ₹449 per year

Premium subscribers get access to monthly and annual horoscopes, unlimited AI chat, and Sun sign monthly/annual forecasts.

### 4. Payment Terms
- Payments are processed securely via Razorpay
- Accepted methods: UPI, Credit/Debit Cards, Net Banking, Wallets
- All prices are in Indian Rupees (INR) inclusive of applicable taxes
- Subscriptions are billed in advance for the chosen period
- We reserve the right to change pricing with 30 days notice

### 5. Refund Policy
- Monthly subscriptions: No refund after the billing date
- Annual subscriptions: Refund of remaining months available within 7 days of purchase, after which no refunds are provided
- Refund requests must be sent to: support@myjyotish-ai.in
- Refunds, if approved, will be processed within 5-7 business days to the original payment method

### 6. Cancellation
You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. No partial refunds for unused periods unless within the refund window stated above.

### 7. User Obligations
You agree not to:
- Use the App for any unlawful purpose
- Attempt to reverse engineer, copy, or redistribute App content
- Share premium account access with others
- Use the App to harass, harm, or defraud others

### 8. Intellectual Property
All content, including AI-generated readings, astrological calculations, and design elements, are the intellectual property of Jyotish. You may not reproduce or distribute content without written permission.

### 9. Third-Party Services
Jyotish uses the following third-party services:
- Google Gemini API (AI generation)
- Swiss Ephemeris (planetary calculations)
- Razorpay (payment processing)
- OpenStreetMap (geocoding)

These services have their own terms and privacy policies.

### 10. Disclaimer of Warranties
The App is provided "as is" without warranties of any kind. We do not guarantee uninterrupted access or that readings will be accurate or meet your expectations.

### 11. Limitation of Liability
To the maximum extent permitted by law, Jyotish shall not be liable for indirect, incidental, special, or consequential damages arising from use of the App.

### 12. Governing Law
These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Hyderabad, Telangana, India.

### 13. Changes to Terms
We may update these Terms at any time. Continued use of the App after changes constitutes acceptance of the new Terms.

### 14. Contact
For any queries: support@myjyotish-ai.in
    `
  },
  privacy: {
    title: 'Privacy Policy',
    icon: '🔒',
    content: `
## Privacy Policy

**Last updated: May 1, 2026**

This Privacy Policy explains how Jyotish ("we", "us") collects, uses, and protects your information when you use our App at myjyotish-ai.in.

### 1. Information We Collect

**Information you provide:**
- Name (first name only, for personalisation)
- Date, time, and place of birth (for chart calculations)
- Demographic information (age group, life stage, interests — for personalisation)
- Email address (only at payment, for receipts)
- Gender (for personalised readings)

**Information collected automatically:**
- Approximate location (via browser geolocation, for day/night theme and local context)
- Device type and browser (for app functionality)
- Usage patterns (which features you use)

### 2. How We Use Your Information
- To calculate your birth chart and generate astrological readings
- To personalise AI-generated horoscopes and chat responses
- To process payments and send receipts
- To improve the App's accuracy and user experience

### 3. Data Storage
- **Birth details are not permanently stored** on our servers. They are processed in real-time to generate your reading and are not retained after your session.
- **Payment data** is handled entirely by Razorpay. We do not store credit card or UPI details.
- **Premium tokens** (JWT) are stored locally on your device only.
- **Location data** is used only during your session and not stored.

### 4. Data Sharing
We do not sell your personal data. We share limited data with:
- **Google** (Gemini API) — anonymised chart parameters for AI generation. Subject to Google's AI data policies.
- **Razorpay** — email and payment details for transaction processing
- **OpenStreetMap** — place name for geocoding (no personal identifiers shared)

### 5. AI and Data Use
Content sent to Google Gemini API may be used by Google to improve their AI models if you are on the free tier. By using AI features, you acknowledge this. We recommend not entering sensitive personal information beyond what is required for chart calculations.

### 6. Cookies and Local Storage
We use browser localStorage to store:
- Your premium subscription token (JWT)
- Your subscription plan

We do not use tracking cookies or advertising cookies.

### 7. Children's Privacy
Jyotish is not intended for users under 18 years of age. We do not knowingly collect data from minors.

### 8. Your Rights
Under applicable law (including India's Digital Personal Data Protection Act 2023), you have the right to:
- Access data we hold about you
- Request deletion of your data
- Withdraw consent at any time

To exercise these rights, contact: support@myjyotish-ai.in

### 9. Data Security
We use HTTPS encryption for all data transmission. Our backend is hosted on Render.com with industry-standard security practices.

### 10. International Users
If you are accessing Jyotish from outside India, your data may be processed in India. By using the App, you consent to this transfer.

### 11. Changes to This Policy
We may update this Privacy Policy from time to time. We will notify users of significant changes via the App.

### 12. Contact
For privacy-related queries: support@myjyotish-ai.in
    `
  },
  refund: {
    title: 'Refund Policy',
    icon: '💰',
    content: `
## Refund Policy

**Last updated: May 1, 2026**

### Overview
At Jyotish, we want you to be completely satisfied with your Premium subscription. This Refund Policy outlines the conditions under which refunds are issued.

### Monthly Subscriptions (₹49/month)
- **No refunds** are issued for monthly subscription charges once the billing date has passed.
- You may cancel at any time to prevent future charges.
- Access continues until the end of the current billing period.

### Annual Subscriptions (₹449/year)
- **Full refund** available within 48 hours of purchase if you have not used any premium features.
- **Pro-rata refund** for remaining months available within 7 days of purchase.
- After 7 days, no refunds are available for annual subscriptions.
- Refund = (₹449 / 12) × remaining full months unused

### How to Request a Refund
1. Email support@myjyotish-ai.in with subject "Refund Request"
2. Include your registered email address and payment ID (from Razorpay receipt)
3. State the reason for your refund request
4. We will respond within 2 business days

### Processing Time
Approved refunds are processed within 5-7 business days. The amount will be credited to your original payment method:
- UPI: 1-3 business days
- Credit/Debit Card: 5-7 business days
- Net Banking: 3-5 business days

### Non-Refundable Situations
- Monthly subscription charges
- Annual subscriptions after 7 days
- Cases where premium features have been extensively used
- Accounts found violating our Terms & Conditions

### Disputes
If you believe you have been charged incorrectly, please contact us at support@myjyotish-ai.in before raising a dispute with your bank or Razorpay.

### Contact
Email: support@myjyotish-ai.in
Response time: Within 2 business days
    `
  }
}

export default function LegalScreen({ onBack, initialSection }) {
  const [activeSection, setActiveSection] = useState(initialSection || 'disclaimer')
  const section = SECTIONS[activeSection]

  const renderContent = (content) => {
    return content.trim().split('\n').map((line, i) => {
      if (line.startsWith('## ')) {
        return <h2 key={i} className="font-serif text-2xl text-slate-900 mt-6 mb-3 font-light">{line.replace('## ', '')}</h2>
      }
      if (line.startsWith('### ')) {
        return <h3 key={i} className="font-semibold text-slate-800 text-sm mt-4 mb-2">{line.replace('### ', '')}</h3>
      }
      if (line.startsWith('- ')) {
        return <div key={i} className="flex gap-2 mb-1"><span className="text-amber-500 mt-0.5">•</span><p className="text-slate-600 text-sm flex-1">{line.replace('- ', '')}</p></div>
      }
      if (line.startsWith('**') && line.endsWith('**')) {
        return <p key={i} className="font-semibold text-slate-800 text-sm mt-2">{line.replace(/\*\*/g, '')}</p>
      }
      if (line.trim() === '') {
        return <div key={i} className="h-2"/>
      }
      // Handle inline bold
      const parts = line.split(/\*\*(.*?)\*\*/g)
      return (
        <p key={i} className="text-slate-600 text-sm leading-relaxed">
          {parts.map((part, j) => j % 2 === 1 ? <strong key={j} className="text-slate-800">{part}</strong> : part)}
        </p>
      )
    })
  }

  return (
    <div className="min-h-screen bg-[#FAFAF8]">
      {/* Header */}
      <div className="bg-white border-b border-slate-100 px-6 pt-12 pb-4 sticky top-0 z-10">
        <button onClick={onBack} className="flex items-center gap-2 text-slate-500 text-sm mb-3">
          ← Back
        </button>
        <h1 className="font-serif text-2xl text-slate-900">Legal & Policies</h1>
      </div>

      {/* Section tabs */}
      <div className="px-4 py-4 flex gap-2 overflow-x-auto">
        {Object.entries(SECTIONS).map(([key, sec]) => (
          <button key={key} onClick={() => setActiveSection(key)}
            className={`flex-shrink-0 px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
              activeSection === key ? 'bg-slate-900 text-white' : 'bg-white border border-slate-200 text-slate-600'
            }`}>
            {sec.icon} {sec.title}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="px-6 pb-16">
        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          {renderContent(section.content)}
        </div>

        <p className="text-center text-xs text-slate-400 mt-6 pb-4">
          For questions: support@myjyotish-ai.in
        </p>
      </div>
    </div>
  )
}